# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    environment:
     TERM: xterm-256color
    working_directory: "/go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}"
    steps:
      - checkout
      - run: go get -d -v -t ./...
      - run: go test -v ./...
      - run: ./scripts/ci_script.sh
      - run: ls
      
