version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: "/go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}"
    steps:
      - checkout
      - run: go get -d -v -t ./...
      - run: go test -v ./...
      - run: ./scripts/ci_script.sh
      - run: ls
      
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
